#ifndef LLRAnalysis_HadTauStudies_MSSMHiggsPtReweightProducerGluGlu_h
#define LLRAnalysis_HadTauStudies_MSSMHiggsPtReweightProducerGluGlu_h

/** \class MSSMHiggsPtReweightProducerGluGlur
 *
 * Reweight MSSM gg -> Higgs events generated by PYTHIA
 * to Higgs Pt spectrum computed by HqT (using infinite quark mass approximation),
 * times a correction for finite bottom and top quark masses computed by HIGLU.
 *
 * Systematic uncertainties on the reweighted Higgs Pt distribution include:
 *  - scale uncertainties from HqT
 *  - scale uncertainties from HIGLU
 *  - uncertainty on relative contribution of top and bottom quark loops (estimated by varying tanBeta between 1 and 60)
 *
 * The procedure for the Higgs Pt reweighting is described in arXiv:hep-ph/0604156 :
 *   "SM and MSSM Higgs Boson Production: Spectra at large transverse Momentum", 
 *   by U. Langenegger, M. Spira, A. Starodumov and P. Trueb
 *
 * \authors Christian Veelken
 *
 */

#include "FWCore/Framework/interface/EDProducer.h"
#include "FWCore/Framework/interface/Event.h"
#include "FWCore/Framework/interface/EventSetup.h"
#include "FWCore/ParameterSet/interface/ParameterSet.h"
#include "FWCore/Utilities/interface/InputTag.h"

#include <TFile.h>
#include <TH1.h>

#include <vector>
#include <string>

class MSSMHiggsPtReweightProducerGluGlu : public edm::EDProducer 
{
 public:
  explicit MSSMHiggsPtReweightProducerGluGlu(const edm::ParameterSet&);
  ~MSSMHiggsPtReweightProducerGluGlu();

  void produce(edm::Event&, const edm::EventSetup&);

 private:
  edm::InputTag srcGenParticles_;
  
  TFile* inputFile_;
  typedef std::vector<double> vdouble;
  vdouble mA_values_;
  vdouble mu_values_;
  typedef std::vector<std::string> vstring;
  vstring higgsTypes_;
  vstring central_or_shifts_;
  std::map<double, std::map<double, std::map<std::string, std::map<std::string, TH1*> > > > luts_; // key = mA_value, mu_value, higgsType, central_or_shift
  std::map<double, std::map<double, std::map<std::string, std::map<std::string, std::string> > > > instanceLabels_; // key = mA_value, mu_value, higgsType, central_or_shift
  
  int maxWarnings_;
  int numWarnings_;
};

#endif

